language: node_js

services:
  - docker

node_js: "node"

git:
  depth:
    1

script:
  - npx @advtr/cli --user travis
  - docker image inspect travis/proxy:development >/dev/null 2>&1
  - docker image inspect travis/proxy:development-local >/dev/null 2>&1

# Around 2.X.X will look at a way to add a tag/push to @advtr/cli
# so this can be done easier without a rebuild
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - npx @advtr/cli --user advtr --push
